navikt/veientilarbeid

src/demo/demo-dashboard.tsx
src/demo/demo-state.ts

Når det gjelder testen må man nesten sette opp en test som kjører i miljøet eller på browserstack - skal forsøke å se litt mer på dette.
Når det gjelder å sette en property i stedet for å sjekke url, tenker jeg at det ikke er noe vits

FO-1898 Fjerner todos

---

src/innhold/innhold.less
src/komponenter/aktivitetsplan/aktivitetsplan.tsx
src/komponenter/dagpenger/dagpenger.less
src/komponenter/dagpenger/dagpenger.tsx
src/komponenter/egenvurdering/egenvurdering.less
src/komponenter/egenvurdering/egenvurdering.tsx
src/komponenter/ressurslenker-jobbsok/ressurslenker-jobbsok.less

- ny bakgrunnsfarge
- boks rundt dagpenger
- boks rundt egenvurdering

[FO-2183] - tilpasse design til Ditt NAV

---

package-lock.json
src/index.less
src/komponenter/dagpenger/dagpenger.less
src/komponenter/dagpenger/dagpenger.tsx
src/komponenter/okonomi/okonomi-panel.less

Gjør dagpenger og egenvurdering mer like

FO-2183 - Tilpasse design

---

src/hotjar.ts
src/innhold/innhold-logikk-niva4.tsx

Bruker erMikrofrontend til å trigger vta-dittnav-generell eller vta-generell

[FO-2323] - ulik Hotjar trigger etter context for app

---

package-lock.json
package.json
src/index.tsx
src/komponenter/aktivitetsplan/aktivitetsplan.tsx

Oppdaterer craco, craco-less og react-scripts.
Bytter fra babel-polyfill til core-js

[KAIZEN-0] - Oppdatering del 2

---

src/innhold/innhold-logikk-niva4.tsx

Reverter den forretningsmessige endringen gjort i 2b3b52eda28da82c63974fb979a870bb779a12cd

Reverter endring foreløpig til vi får diskutert konsekvensene skikkelig

---

public/frontendlogger/logger.js

Legger til dummyfil for å forhindre error lokalt

---

src/innhold/innhold-logikk-niva4.tsx
src/metrics/metrics.ts

underOppfolging
registreringType
fremtidigSituasjon

[KAIZEN-0] - legger inn flere metrikker

---

src/komponenter/innsyn/registreringsopplysninger.tsx
src/komponenter/registrert/registrert.tsx

- endrer tekst (fjerner se under)
- stopper dobbel logging på metrikk

[KAIZEN-0] - Oppdatering innsyn

---

.github/workflows/deploy.yml
.nowignore
now-screenshots.json
now.json

- deploy til demo ved push
- ta skjermbilder av demo ved push

Screenshots

---

src/innhold/innhold-logikk-niva4.tsx

Skrus på 12/03-20 kl 00:00 for minst mulig overlapp mellom møtestøtte del 1 & 2

Endrer dato for møtestøtte

---

src/innhold/innhold-logikk-niva4.tsx

Brukere med servicegruppe satt til BKART og foreslått innsatsgruppe
satt til ARBS skal se møtestøtte inngangen

KAIZEN-0: BKART skal vise møtestøtte

---

src/demo/demo-state.ts
src/ducks/feature-toggles.ts
src/komponenter/meldekort/meldekort.tsx
src/mocks/feature-toggles-mock.ts
src/tekster/tekster.ts

Skal gjøre det enklere for bruker å forstå hvordan man finner ulike operasjoner for meldkort.
Innspill fra HotJar undersøkelse kan tyde på at det ikke er helt opplagt.

Endrer tekst for meldekort, lagt bak featureToggle (patch)

---

src/ducks/feature-toggles.ts
src/innhold/innhold-logikk-niva3.tsx
src/innhold/innhold-logikk-niva4.tsx
src/innhold/innhold-view.tsx
src/komponenter/dialog/dialog-permittert.tsx
src/mocks/feature-toggles-mock.ts

- hvis permittert og toggle er slått på legges dialogboks over aktivitetsplan og meldekort
- dialogboksen inneholder en litt annen tekst
- erPermittert styres av toggle og at dinSituasjon er satt til permittert ved registrering

Lager ny dialogboks og plassering for de som er permitterte

---

src/komponenter/dialog/dialog-permittert.tsx
src/metrics/metrics.ts

- veientilarbeid.gatildialogpermittert

Legger til egen metrikk for permittert dialog (patch)

---

nais/nais.yaml
nais/vars-p.yaml
nais/vars-q0.yaml
nais/vars-q1.yaml

For at byEnvironment strategi i Unleash skal fungere.

Legg til FASIT_ENVIRONMENT_NAME miljøvariabel

---

package-lock.json
package.json
src/innhold/rad.tsx
src/komponenter/din-situasjon/situasjon.tsx
src/komponenter/meldinger/trekk-dp-soknad.tsx
src/komponenter/motestotte/motestotte.tsx
src/metrics/metrics.ts
src/metrics/uni-logger.ts

- oppdaterer amplitude sdk
- legger til amplitude/unilogger flere steder på metrikker

Mer amplitude

---

src/komponenter/din-situasjon/person-med-blyant.tsx
src/metrics/metrics.ts

- legger amplitude på resterende metrikker
- fikser svg properties til jsx format

Legger til mer amplitude

---

decorator.yaml
nais/nais.yaml
nais/vars-p.yaml
nais/vars-q0.yaml
nais/vars-q1.yaml
src/innhold/lenker.ts

Oppdaterte også prod linken for aktivitetsplan, den som lå der var utdatert

Legg til ny dialog url

---

src/ducks/bruker-info.ts
src/innhold/innhold-logikk-niva4.tsx
src/mocks/bruker-info-mock.ts
src/utils/get-poa-group.test.ts
src/utils/get-poa-group.ts

- legger til alder fra `/startregistrering`
- bruker alder til å sette poa-gruppe

Alder i poagruppe

---

src/innhold/innhold-logikk-niva4.tsx
src/utils/get-poa-group.test.ts
src/utils/get-poa-group.ts

Et nytt krav for kss i poagruppefilteret er nå at det er under 16 uker siden registreringsdato.

Spisser poagruppefilter til å kreve under 16 uker for kss

---

src/komponenter/din-situasjon/situasjon.less
src/komponenter/din-situasjon/situasjon.tsx

Overskrivingen av h2 paavirket ogsaa nav-dekoratoeren

Fjerner tilsynelatende ubrukt css

---

package-lock.json
src/utils/get-poa-group.test.ts
src/utils/get-poa-group.ts

- øker aldersspennet til 55 år
- lager array for situasjoner for senere utvidelse
- lager variabler for høyeste og laveste alder

kssfilter oppdatering

---

package-lock.json
src/innhold/innhold-logikk-niva3.tsx
src/innhold/innhold-logikk-niva4.tsx
src/innhold/innhold-view.tsx
src/komponenter/aktivitetsplan/aktivitetsplan.tsx
src/komponenter/dialog/dialog.tsx
src/komponenter/meldekort/meldekort.tsx
src/metrics/metrics.ts

Starter å logge aktivitet kombinert med poagruppe

kss logg aktivitet

---

README.md
package-lock.json
src/innhold/innhold-view.tsx
src/komponenter/alleskjema/alleskjema.tsx
src/komponenter/dagpenger/dagpenger.tsx
src/komponenter/meldinger/trekk-dp-soknad.tsx
src/komponenter/okonomi/okonomi-rad-dagpenger.tsx
src/komponenter/paminnelser/sjekk-kontonummer.tsx
src/komponenter/ressurslenker-jobbsok/cv.tsx
src/komponenter/ressurslenker-jobbsok/jobbsokertips.tsx
src/komponenter/ressurslenker-jobbsok/ressurslenker-jobbsok.tsx
src/komponenter/ressurslenker-jobbsok/stillingsok.tsx

Logger flere aktiviteter
- cv
- jobbsøkertips
- ledige stillinger
- dagpengesøknad
- all skjema
- oppdatere kontoinformasjon
- trekk dagpangesøknad

kss logge flere aktiviteter

---

package-lock.json
src/innhold/innhold-view.tsx
src/komponenter/dialog/dialog-permittert.tsx
src/komponenter/dialog/dialog.tsx

Fikser manglende logg av aktivitet på dialogen

Dialogsjekk

---

package-lock.json
package.json

Samler alle oppdateringer fra Snyk

Snyk 20200701

---

package-lock.json
package.json

- Samler oppdateringene fra Snyk

Snyk 20200702

---

package-lock.json
package.json

Snyk 20200703

---

README.md
src/hotjar-create-trigger-type.test.ts
src/hotjar.ts
src/innhold/innhold-logikk-niva4.tsx

- Legger inn støtte i `hotjarTrigger` for isExperiment (boolean)
- Legger inn funksjon for å sette opp kriterier for fremtidige eksperimenter

Klargjør for eksperimenter som skal kunne trigge egne HotJars

---

package-lock.json
package.json

Snyk 20200810

---

package-lock.json
package.json

Snyk 20200811

---

package-lock.json
package.json

Snyk 20200813

---

package-lock.json
package.json

Oppdaterer diverse dependencies og devDependencies

Oppdateringer 20200907

---

src/innhold/innhold-logikk-niva4.tsx
src/metrics/metrics.ts
src/utils/is-kss-eksperiment.test.ts
src/utils/is-kss-eksperiment.ts

- Legger til funksjonalitet for å kunne si om en bruker er deltager av kss-eksperimentet eller ei.
- Legger til egen telling i Amplitude for deltagerei eksperimentet

Eksperimentfilter

---

package-lock.json
package.json
src/innhold/innhold-logikk-niva3.tsx
src/innhold/innhold-logikk-niva4.tsx
src/innhold/innhold-view.tsx
src/komponenter/aktivitetsplan/aktivitetsplan.tsx
src/komponenter/alleskjema/alleskjema.tsx
src/komponenter/dagpenger/dagpenger.tsx
src/komponenter/dialog/dialog-permittert.tsx
src/komponenter/dialog/dialog.tsx
src/komponenter/meldekort/meldekort.tsx
src/komponenter/meldinger/trekk-dp-soknad.tsx
src/komponenter/okonomi/okonomi-rad-dagpenger.tsx
src/komponenter/paminnelser/sjekk-kontonummer.tsx
src/komponenter/registrert/registrert.tsx
src/komponenter/ressurslenker-jobbsok/cv.tsx
src/komponenter/ressurslenker-jobbsok/jobbsokertips.tsx
src/komponenter/ressurslenker-jobbsok/ressurslenker-jobbsok.tsx
src/komponenter/ressurslenker-jobbsok/stillingsok.tsx
src/metrics/amplitude-utils.ts
src/metrics/metrics.ts

- Legger inn antall uker fra registrering som en del av fast pakke som logger til Amplitude
- Rydder opp og lager interface, typer og datapakke til Amplitude som brukes hele veien for å kunne enkelt utvide senere

Legge inn uker fra registrering

---

package-lock.json
src/innhold/innhold-logikk-niva3.tsx
src/innhold/innhold-logikk-niva4.tsx
src/metrics/amplitude-utils.ts
src/utils/get-poa-group.test.ts
src/utils/get-poa-group.ts
src/utils/is-kss-kontroll.test.ts
src/utils/is-kss-kontroll.ts

- innfører isKSSK for å identifisere kontrollgruppen til eksperimentet
- fjerner "ER_PERMITTERT" fra gyldige kss-situasjoner for å matche eksperimentet
- reduserer tidsperiode fra 16 til 12 uker for å matche eksperimentet

Flere endringer på kss-filter

---

package-lock.json
package.json

Oppdateringer forslått fra Snyk og et par andre avhengigheter som var modne for plukking

Snyk20201001

---

package-lock.json
package.json

Dagens fra Snyk i tillegg til de andre avhengighetene som var modne for oppdatering.

Snyk 20201012

---

.github/workflows/deploy.yml
now-screenshots.json
now.json
package-lock.json

- oppdateringer for å deploye demoversjon til Vercel

vercel demo

---

package-lock.json
src/komponenter/innsyn/registreringsopplysninger.tsx
src/utils/pretty-print-dato.ts

- gjenbruker utils/pretty-print-dato på innsynet for registrering
- fjerner duplisert og ubrukt kode fra innsynskomponenten

Penere dato

---

.github/workflows/deploy.yml
src/index.tsx
src/komponenter/hent-initial-data/sjekk-oppfolging.tsx

Standalone-varianten av tjenesten skal ikke lenger være tilgjengelig for annet en mock/demo.

Standalone redirect til Ditt NAV

---

package-lock.json
src/innhold/innhold-view.tsx
src/komponenter/egenvurdering/egenvurdering.tsx

Legger enn ny tracking til amplitude på egenvurdering.
Vi ønsker å kunne si noe om hvorvidt kss-brukere ser den og om den benyttes eller ei.

Egenvurdering amplitude

---

src/utils/is-kss-eksperiment.ts

Legger inn nummer for begge bydelene

Hillevåg Hinna

---

package-lock.json
package.json
src/komponenter/aktivitetsplan/aktivitetsplan.tsx
src/komponenter/alleskjema/alleskjema.tsx
src/komponenter/dagpenger/dagpenger.tsx
src/komponenter/egenvurdering/egenvurdering.tsx
src/komponenter/meldekort/meldekort.tsx
src/komponenter/meldinger/trekk-dp-soknad.tsx
src/komponenter/paminnelser/sjekk-kontonummer.tsx
src/komponenter/registrert/registrert.tsx
src/metrics/metrics.ts

- lar amplitude bli enerådende på flere områder

Amplitude fix

---

package-lock.json
src/innhold/innhold-logikk-niva4.tsx
src/komponenter/meldekort/meldekort.tsx
src/komponenter/ressurslenker-jobbsok/cv.tsx
src/komponenter/ressurslenker-jobbsok/jobbsokertips.tsx
src/komponenter/ressurslenker-jobbsok/stillingsok.tsx
src/metrics/metrics.ts

- legger inn aktivitet for visning av siden
- fjerner flere av loggingene som ikke går til Amplitude

Amplitude aktivitet utvidelse

---

package-lock.json
package.json

Snyk 20201103

---

package-lock.json
package.json
src/innhold/innhold-view.tsx
src/komponenter/iarbs-melding/iarbs-melding.test.tsx
src/komponenter/iarbs-melding/iarbs-melding.tsx

- legger til @testing-library/jest-dom
- legger inn test for iarbs-melding
- refaktorerer komponenten

Refactor iarbs melding

---

src/innhold/innhold-logikk-niva3.tsx
src/innhold/innhold-logikk-niva4.tsx
src/innhold/innhold-view.tsx
src/komponenter/krr-melding/krr-melding.test.tsx
src/komponenter/krr-melding/krr-melding.tsx

- gjør krr helt selvgående
- oppdaterer testene

Krr selvgaende

---

package-lock.json
package.json
src/komponenter/alleskjema/alleskjema.test.tsx
src/komponenter/alleskjema/alleskjema.tsx

Alle skjema

---

package-lock.json
src/komponenter/dagpenger/dagpenger.test.tsx
src/komponenter/dagpenger/dagpenger.tsx

- legger inn test av dagpenger-komponenten

Dagpenger test

---

src/komponenter/innsyn/registreringsopplysninger.test.tsx

- tester at komponent rendres
- tester at link kan trykkes på

Legger til test av registreringsopplysninger

---

package-lock.json
src/komponenter/registrert/registrert.test.tsx
src/test/test-context-providers.tsx

- legger autentisering inn i test-context
- lager test for rendring av registreringskomponenten

Registrering test

---

package-lock.json
src/komponenter/paminnelser/sjekk-kontonummer.test.tsx
src/komponenter/paminnelser/sjekk-kontonummer.tsx
src/komponenter/registrert/registrert.test.tsx
src/test/test-context-providers.tsx

- legger inn sjekk av oppfølgingsstatus og innloggingsnivå i komponenten
- legger inn test av komponenten

Paaminnelser test

---

src/komponenter/meldinger/trekk-dp-soknad.test.tsx
src/komponenter/meldinger/trekk-dp-soknad.tsx
src/komponenter/paminnelser/sjekk-kontonummer.tsx

- legger til sjekk av innlogingsnivå og oppfølgingsstatus
- legger til test av komponent

Meldinger test

---

src/komponenter/aap/aap.test.tsx
src/komponenter/banner/banner.test.tsx
src/komponenter/meldinger/trekk-dp-soknad.test.tsx
src/komponenter/paminnelser/sjekk-kontonummer.test.tsx
src/komponenter/registrert/registrert.test.tsx

Legg til `ProviderProps`-type der det manglet, for å lettere avdekke typefeil. Fikset også feilene dette avdekket.

Typescript typer

---

package-lock.json
src/komponenter/ditt-sykefravaer/ditt-sykefravaer.test.tsx
src/komponenter/ditt-sykefravaer/ditt-sykefravaer.tsx

- Legger inn logikk for visning av komponenten
- Legger til tester av komponenten

Sykefravaer test

---

src/komponenter/meldekort/meldekort.test.tsx
src/komponenter/meldekort/meldekort.tsx

- lar komponenten selv avgjøre om den skal vises
- legger inn test av komponent

Meldekort test

---

package-lock.json
src/komponenter/meldekort/meldekort.test.tsx
src/komponenter/meldekort/meldekort.tsx

Sørger for at meldekort også vises på nivå 3

Meldekort level 3

---

src/ducks/amplitude-aktivitet-context.ts
src/komponenter/aap/aap.tsx
src/komponenter/aktivitetsplan/aktivitetsplan.tsx
src/komponenter/alleskjema/alleskjema.tsx
src/komponenter/dagpenger/dagpenger.tsx
src/komponenter/dialog/dialog.tsx
src/komponenter/ditt-sykefravaer/ditt-sykefravaer.tsx
src/komponenter/hent-initial-data/amplitude-provider.tsx
src/komponenter/iarbs-melding/iarbs-melding.tsx
src/komponenter/innsyn/registreringsopplysninger.tsx
src/komponenter/meldekort/meldekort.tsx
src/komponenter/meldinger/trekk-dp-soknad.tsx
src/komponenter/motestotte/motestotte.tsx
src/komponenter/paminnelser/sjekk-kontonummer.tsx
src/komponenter/reaktivering-melding.tsx
src/komponenter/registrert/registrert.tsx
src/metrics/amplitude-utils.ts
src/metrics/metrics.ts

- legger til visningslogg på alle komponenter som manglet det

Amplitude logg likt

---

package-lock.json
src/komponenter/meldinger/trekk-dp-soknad.test.tsx
src/komponenter/meldinger/trekk-dp-soknad.tsx
src/komponenter/paminnelser/sjekk-kontonummer.test.tsx
src/komponenter/paminnelser/sjekk-kontonummer.tsx

- viser sjekk kontonummer også for nivå 3
- viser trekk dp-søknad også for nivå 3

Nivaa3 meldinger

---

src/utils/is-kss-eksperiment.test.ts
src/utils/is-kss-eksperiment.ts

- legger inn sluttdato for kssx t.o.m. 30. november 2020

Setter avslutningsdato for eksperimentet

---

package-lock.json
src/innhold/innhold-view.tsx
src/komponenter/dittnav/generelle-fliser.tsx

- legger generelle fliser i samme rad som de andre komponenten

Fjerner luft ned til generelle fliser

---

src/komponenter/reaktivering/reaktivering-melding.less
src/komponenter/reaktivering/reaktivering-melding.test.tsx
src/komponenter/reaktivering/reaktivering-melding.tsx

Vi forsøker å forbedre teksten som vises for de som får "kanReaktivering".
Slik ser den ut tidligere
Slik ser den ut nå

Endre reaktiveringstekst

---

src/komponenter/hent-initial-data/amplitude-provider.tsx
src/utils/grupper-geografisk-tilknytning.test.ts
src/utils/grupper-geografisk-tilknytning.ts

- slår sammen til fylkesnivå på det som sendes til Amplitude

Gruppering geografisk tilknytning

---

src/hooks/use-localstorarge.js
src/innhold/innhold-view.tsx
src/komponenter/reaktivering/reaktivering-ikke-aktuelt-melding.test.tsx
src/komponenter/reaktivering/reaktivering-ikke-aktuelt-melding.tsx
src/komponenter/reaktivering/reaktivering-kort.test.tsx
src/komponenter/reaktivering/reaktivering-kort.tsx
src/komponenter/reaktivering/reaktivering-melding.less
src/komponenter/reaktivering/reaktivering-melding.test.tsx
src/komponenter/reaktivering/reaktivering-melding.tsx

Lager en løsning hvor bruker kan si at de ikke lenger har behov for å være registrert hos NAV når de får tilbud om reaktivering.
Slik ser den ut før man velger at det er riktig at man ikke lenger er registrert
Slik ser det ut etter valget

Lukk reaktivering

---

src/innhold/innhold-metrics.tsx
src/komponenter/hent-initial-data/amplitude-provider.tsx
src/mocks/meldekort.json
src/utils/meldekort-dager-til-siste-frist.js
src/utils/meldekort-dager-til-siste-frist.test.js

- tester av dager til frist metoden

Metrikker for reell visning av vta

---

src/innhold/innhold-metrics.tsx

Endrer fra å rette seg mot kanReaktiveres til de som ikke har sendt inn meldekort i tide.

Endrer innholdet for HotJar eksperimentet

---

package-lock.json
src/ducks/amplitude-context.ts
src/innhold/innhold-metrics.tsx
src/komponenter/aap/aap.tsx
src/komponenter/aktivitetsplan/aktivitetsplan.tsx
src/komponenter/alleskjema/alleskjema.tsx
src/komponenter/dagpenger/dagpenger.tsx
src/komponenter/dialog/dialog.tsx
src/komponenter/ditt-sykefravaer/ditt-sykefravaer.tsx
src/komponenter/egenvurdering/egenvurdering.tsx
src/komponenter/hent-initial-data/amplitude-provider.tsx
src/komponenter/krr-melding/krr-melding.tsx
src/komponenter/meldekort/meldekort.tsx
src/komponenter/meldinger/trekk-dp-soknad.tsx
src/komponenter/motestotte/motestotte.tsx
src/komponenter/paminnelser/sjekk-kontonummer.tsx
src/komponenter/reaktivering/reaktivering-ikke-aktuelt-melding.tsx
src/komponenter/reaktivering/reaktivering-melding.tsx
src/komponenter/registrert/registrert.tsx
src/metrics/amplitude-utils.ts
src/metrics/metrics.ts

- splitter hovedmålingene i aktivitet og visning
- fjerner logging av visning på de fleste boksene da vi kan bruke "Viser i viewPort" som indikasjon på at de har scrollet ned
- fjerner dobbeltlogging til andre metrikknavn
- fjerner ubrukte metrikker
- legger til mer fast info i amplitudeData

Amplitude splitter visning og aktivitet

---

package-lock.json
src/ducks/amplitude-context.ts
src/innhold/innhold-metrics.tsx
src/komponenter/hent-initial-data/amplitude-provider.tsx
src/metrics/amplitude-utils.ts

- fra antallDagerFraPeriodeslutt til antallDagerEtterFastsattMeldingsdag slik at metrikken faktisk heter det den måler

Endrer metrikknavn 

---

package-lock.json
src/ducks/amplitude-context.ts
src/komponenter/hent-initial-data/amplitude-provider.tsx
src/metrics/amplitude-utils.ts

- legger til erSamarbeidskontor som fast amplitude-metrikk
- gir `ja` på alle brukere med `geografiskTilknytning` til kontorer som var pilot eller kontrollkontor på kss-eksperimentet og `nei` på alle andre

Er tilknyttet eksperiment kontor

---

src/hooks/use-browserstorage.ts
src/utils/browserStorage-support.test.ts
src/utils/browserStorage-support.ts
src/utils/browserStorage-utils.ts

Fallback for localStorage med et javascript-objekt for når localStorage ikke er tilgjengelig, eller har feil.

Localstorage fallback

---

src/komponenter/14a-intro/14a-intro.test.tsx
src/komponenter/14a-intro/14a.tsx
src/komponenter/meldekortintro/meldekort-intro.test.tsx
src/komponenter/meldekortintro/meldekort-intro.tsx
src/komponenter/meldekortintro/pre-state.tsx

Legger til tydelig inViewport for pre-statene til meldekortintro og 14a onboarding

Spesifikk pre state

---

decorator.yaml
nais/nais.yaml
nais/vars-dev-paw.yaml
nais/vars-p.yaml
nais/vars-q0.yaml
nais/vars-q1.yaml

Setter opp proxy fra `/tjenester` til `tjenester.nav.no` for å kunne få tak i bl.a. saksapiet

Tjenester proxy

---

decorator.yaml
nais/nais.yaml
nais/vars-dev-paw.yaml
nais/vars-p.yaml
nais/vars-q0.yaml
nais/vars-q1.yaml

endrer fra tjenester til saksoversikt-api

Saksoversikt proxy

---

package-lock.json
package.json

- oppdateringer fra Snyk
- oppdaterte ds-icons og amplitude-js

Snyk 210527

---

.github/workflows/deploy.yml
src/ducks/amplitude-context.ts
src/ducks/mulige-ettersendelser.ts
src/komponenter/hent-initial-data/amplitude-provider.tsx
src/komponenter/hent-initial-data/data-provider.tsx
src/metrics/amplitude-utils.ts

- legger til context og provider for påbegynte søknader
- legger til context og provider for mulige ettersendelser
- legger til context og provider for sakstema
- legger til dagpengemetrikker for amplitude

Saksoversikt api context og provider

---

package-lock.json
package.json

Snyk 210601

---

src/komponenter/onboarding-ytelser/dagpenger/sluttkort-har-ikke-sokt.tsx
src/komponenter/onboarding-ytelser/ytelser-onboarding.tsx
src/komponenter/tema/tema.tsx
src/lib/har-ikke-startet-dagpengesoknad.ts

Dette ble litt knotete fordi boksen er nøsta gjennom flere filer/komponenter. Jeg så ingen enkel måte å bare legge styling rett på boksen, for enten ble det for langt ute til at vi vet om det er det blå kortet som skal vises, ellers ble det for langt inne i komponenten til at jeg fikk stylet hele boksen. Bare å endre på det om noen ser en enklere fiks.

f Vis blått onboardingkort når man ikke har søkt dagpenger

---

src/demo/demo-dashboard.css
src/demo/demo-dashboard.tsx

For de som er vant til den gamle layouten, funker dette greit?

styling demo

---

src/komponenter/registrert/registrert.tsx
src/komponenter/registrert/status-tittel.tsx

Trenger ikke review, skal merges og deployes mandag morgen.

f Scroll så tittelen havner øverst i vinduet - venter med deploy til mandag

---

src/demo/setup-demo-mock.ts
src/komponenter/onboarding-standard/onboarding-standard.tsx

Henter dato påny når modalen lukkes

Rerender ved dato

---

package-lock.json
package.json
src/innhold/innhold-view.tsx
src/komponenter/innsyn/innsyn-les-mer.tsx
src/komponenter/innsyn/registreringsopplysninger.tsx
src/komponenter/registrert/status-tittel.tsx

Flytter innsyn inn i status for registreringen igjen som en ReadMore-komponent

Statustittel med innsyn

---

src/innhold/innhold-standard.tsx
src/komponenter/dagpenger/bytt-visning-lenke.tsx
src/komponenter/dagpenger/dagpenger-og-ytelser-innhold.tsx
src/komponenter/dagpenger/dagpenger-og-ytelser.tsx
src/komponenter/hjelp-og-stotte/dialog-knapp.tsx
src/komponenter/hjelp-og-stotte/forklaring-engelsk.tsx
src/komponenter/hjelp-og-stotte/forklaring-norsk.tsx
src/komponenter/hjelp-og-stotte/hjelp-og-stotte.tsx

Manda morra merge

---

src/contexts/feature-toggles.ts
src/contexts/gjelder-fra-dato.tsx
src/contexts/profil.tsx
src/demo/demo-state-profil.ts
src/demo/demo-state.ts
src/demo/setup-demo-mock.ts
src/ducks/api-utils.ts
src/komponenter/hent-initial-data/data-provider.tsx

Legger opp til at hvorvidt bruken av profil trår i kraft styres av en featureToggle.
Starter også på profil i demo-sammenheng

Profil i demo og toggle

---

src/contexts/behov-for-veiledning.tsx
src/ducks/api.ts
src/komponenter/innsyn/registreringsopplysninger.tsx

Laget provider(copypasta fra profil) og lagt til url til endepunktet, men har ikke tatt det i bruk.
De andre commitene er bare annet smårusk.

Behov for veiledning context

---

src/contexts/dp-innsyn-paabegynte-soknader.ts
src/komponenter/dagpenger/dagpenger-har-paabegynt-soknad.tsx
src/komponenter/dagpenger/paabegynte-soknader.tsx

For å støtte både gamle og nye søknader går vi over til å bruke "endreLenke" fra dp-innsyn

Ny fortsett søknad om dagpenger url

---

package-lock.json
package.json
public/mockServiceWorker.js

- oppdaterer dependencies
- oppdaterer devDependencies

Oppdateringer 2022 11 28

---

package-lock.json
package.json
public/mockServiceWorker.js

- oppdaterer dependencies
- oppdaterer devDependencies

Oppdateringer 2023 01 30

---

src/innhold/innhold-arbeidssoker-forenklet.tsx
src/innhold/innhold-situasjonsbestemt.tsx
src/innhold/innhold-standard.tsx
src/komponenter/ikke-standard/forenklet-innhold.tsx
src/komponenter/innsyn/periodeopplysninger.tsx
src/komponenter/innsyn/registreringsopplysninger.test.tsx
src/komponenter/innsyn/registreringsopplysninger.tsx
src/komponenter/min-situasjon/min-situasjon.tsx
src/komponenter/min-situasjon/sammendrag.tsx
src/komponenter/registrert-tittel/registrert-tittel.tsx
src/komponenter/situasjonsbestemt/situasjonsbestemt.tsx
src/spacing.module.css

For å starte arbeidet med endring av situasjon for registrerte arbeidssøkere lager vi en ny komponent for å skille situasjon fra registreringen og arbeidssøkerperioder.
Dette er første trinn på veien og gjør ikke annet enn å trekke noen opplysninger ut fra innsynskomponenten og skille opplysningene fra registreringstittelen.

Min situasjon
